# -*- coding: utf-8 -*-
"""GMC_first_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VBSGp8vwh1WHVFz5C0qE-rmRCiPssos

# Welcome to the world of Python!

### Introducting The Print Function

`print` is a built-in function in python

# Welcome to the world of Python!

We'd write our first lines of code in Python today! Yayyy!

### Introducing The Print Function

`print` is a built-in function in Python
Python is case sensitive i.e Print != print
"""

print("Hello World")

print("My name is Demilade")

print("I'm learing about github and I am going to add my work to a repository I cloned")

